# Nixpacks configuration for Railway Streamlit deployment

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false"

[variables]
PYTHON_VERSION = "3.11"
